Vagrant.configure("2") do |config|
    
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.network "public_network"
    end  
    
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64"
      web02.vm.network "public_network"
    end  

    config.vm.define "ansible" do |ansible|
        ansible.vm.box = "ubuntu/focal64"
        ansible.vm.network "public_network"
    end
end    